revert: remove qt core dep

diff --git a/.github/workflows/qt-msvc-build-and-release.yml b/.github/workflows/qt-msvc-build-and-release.yml
--- a/.github/workflows/qt-msvc-build-and-release.yml
+++ b/.github/workflows/qt-msvc-build-and-release.yml
@@ -80,6 +80,31 @@ jobs:
               Write-Host "Directory not found: $buildDir"
           }
 
+      - name: Deploy Qt
+        shell: pwsh
+        run: |
+          # Navigate to the directory containing the executable
+          cd build
+
+          # Use the found path to windeployqt
+          $windeployqtPath = "D:\a\Sunshine-Toolbox\Qt\6.7.2\msvc2019_64\bin\windeployqt6.exe"
+
+          # Check if the executable exists
+          if (Test-Path $windeployqtPath) {
+              # Run windeployqt with the updated options
+              & $windeployqtPath `
+                  --exclude-plugins qmodernwindowsstyle,qsvgicon,qsvg,qico,qjpeg,qgif,qnetworklistmanager,qtuiotouchplugin `
+                  --no-opengl-sw `
+                  --no-system-dxc-compiler `
+                  --no-compiler-runtime `
+                  --no-translations `
+                  --no-system-d3d-compiler `
+                  D:\a\Sunshine-Toolbox\Sunshine-Toolbox\build\release\Sunshine-Toolbox.exe
+          } else {
+              Write-Error "windeployqt not found at the expected path!"
+              exit 1
+          }
+
       - name: Rename release folder
         shell: pwsh
         run: |
